[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./stunserver --primaryport 3478"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "stun-server"
port = 3478 